stages:
  prepare:
    cmd: python prepare.py
    deps:
    - data/data
    - prepare.py
    outs:
    - data/prepared_data
  train:
    cmd: python train.py
    deps:
    - data/prepared_data
    - train.py
    outs:
    - model/my_model.h5
